### ISSUE TITLE
Links to online wallet should go to bitshares.org/wallet

### ISSUE THREAD

**Issue by jonnybitcoin** [bitshares/bitshares.github.io-old#104]
Links to online wallet should go to bitshares.org/wallet not bitshares.openledger.info
- Openledger is a custom front end GUI from a private company
- It doesn't display collateral positions
- Code is not open source
- It is confusing for noobs who might be confused why they aren't being linked to the main bitshares GUI

**Comment by svk31** [comment]
I agree, I'll fix it with the next release.
