### ISSUE TITLE
OS X Download Link is 404

### ISSUE THREAD

**Issue by indolering** [bitshares/bitshares.github.io-old#62]
The website's current OS X link is 404: https://github.com/bitshares/bitshares-2/releases/download/v2.0.151101/BitShares-light_2.0.151103.dmg

I would have submitted a PR but the all of the links appear to be lagging a few patch versions.

**Comment by c055** [comment]
https://github.com/bitshares/bitshares.github.io/commit/d1f5d8723897203191a7b0ed49f5f3e605529bb0

**Comment by c055** [comment]
thx man for reporting .. hope you're doing well :)
