### ISSUE TITLE
can you add the telegram chat group to the website 

### ISSUE THREAD

**Issue by jonnybitcoin** [bitshares/bitshares.github.io-old#81]
Under explore at the bottom of the website can you add a link to the telegram chat room please?

this link will open the  chat window, theres 97 people in this chat room and its like a customer support channel 

https://telegram.me/joinchat/BYoMpwH95HL-crZbLpMiAA

**Comment by c055** [comment]
yup

**Comment by c055** [comment]
https://github.com/bitshares/bitshares.github.io/commit/256c853a9b69a96712e0ddabdfa60fb6892c39ee

**Comment by c055** [comment]
when trying to execute telegram link i'm getting an 404 .. after shortly be able to see the telegram splash ...can u double check it pls?

**Comment by jonnybitcoin** [comment]
sorry, this one works:  https://web.telegram.org/#/im?p=g33416306

**Comment by c055** [comment]
https://github.com/bitshares/bitshares.github.io/commit/368d058ff87ccd2614aabe3d909a7a57309b2412
