### ISSUE TITLE
Add the forum link to the top of the page 

### ISSUE THREAD

**Issue by jonnybitcoin** [bitshares/bitshares.github.io-old#83]
Lots of people have complained that when visiting the bitshares home page for the first time it looks as though the community isn't very active and bts is just another scamcoin. As the forum is the beating heart of the community shouldn't it be at the top of the page in the menu.

**Comment by c055** [comment]
https://github.com/bitshares/bitshares.github.io/commit/27cb9d743e71693829862f24efa9636c78d6ebfb

**Comment by cassiopaia** [comment]
mh but this linke i'm getting an error when trying to execute ...can u double check it pls?
