### ISSUE TITLE
make online wallet link to bitshares.org/wallet instead of bitshares.openledger.info

### ISSUE THREAD

**Issue by jonnybitcoin** [bitshares/bitshares.github.io-old#87]
make online wallet link to bitshares.org/wallet instead of bitshares.openledger.info

**Comment by c055** [comment]
feedback appreciated .. @xeroc and @valzav

**Comment by abitmore** [comment]
I'd rather like to see a list of providers. OpenLedger, BitShares.org, DACPlay, and maybe TheDex?

**Comment by valzav** [comment]
Currently only OpenLedger is functional. bitshares.org/wallet uses OpenLedger behind..
