### ISSUE TITLE
the main text in the middle of the screen doesn't mean much.

### ISSUE THREAD

**Issue by jonnybitcoin** [bitshares/bitshares.github.io-old#92]
"BitShares 2.0 is an industrial-grade financial smart contract platform."

doesn't say what it does. 

something more simple and explanatory would be better such as:

"Welcome to the the decentralised exchange"

or 

"Bitshares 2.0 is an exchange on a blockchain"

or 

"decentralised dollars traded on a blockchain"

**Comment by c055** [comment]
Bitshares 2.0 is an exchange on a blockchain

it's by far more and i'm thinking .. the headline is choosen well .. thoughts @bytemaster @xeroc ?

**Comment by valzav** [comment]
I would rather had more stress on platform rather on DEX. So the tag line can be  something like this: "BitShares is an industrial-grade blockchain smart contracts platform with embedded decentralize exchange"

**Comment by xeroc** [comment]
I agree with @valzav .. even though most people think BTS is about an exchange .. it is way more than that .. it's a real-time capable, turing complete, flexible and decentral governed ecosystem :dart:

**Comment by valzav** [comment]
In the sub header I would stress out that BitShares is a DAC and DEX is its product/application

**Comment by c055** [comment]
i would advise KISS .. as longer and complicated the headline and sub claim sounds .. the more users will go away .. as we are promoting a complex financial product palette .. i would work in the 2-3 step way ... small bits of information -- and then ---> are u interested more -.. then look here ..etc..

Like for insurance are adeverting their products as well .. IMO it should be a guided process

**Comment by jonnybitcoin** [comment]
"industrial grade " is a meaningless term 

it maybe a smart contract platform but right now it does exchanging transferring with a basic derrivative called a smartcoin. the main thing bitshares is today is a decentralised exchange and that is something people can understand. we need a clear simple message  
Also it is not at speeds approaching nasdaq.

**Comment by valzav** [comment]
@jonnybitcoin, I agree on "industrial grade" and "nasdaq speeds", let's remove these statements.
On DEX vs. platform - I think bitshares.org should have more stress on BitShares as platform mentioning DEX as a product built on this platform; openledger.info and thedex.org should feature its DEX side.

**Comment by jonnybitcoin** [comment]
Is this getting updated soon? generally the whole website aswell?

**Comment by valzav** [comment]
As far as I know nobody is working on this. All it takes to update the website is to submit your pull requests to this repo or alternatively just create an issue here and specify clearly what needs to be changed - I think I'll have time to go over the issues next week and update the website. Or just send me pm in Telegram.

**Comment by c055** [comment]
i'm starting this week in a redesign of the site...!

**Comment by abitmore** [comment]
Do we really need a redesign? Won't it need too much man hour?

**Comment by c055** [comment]
will do it .. no matter .. the community was patient the past weeks were i ws facing huge private challanges .. i would love to say thank you .. but yes .. maybe wrong wording .. i will tweak the complete site .. but idk if i will make it completely new.. hope this will answer your question .. :)

**Comment by abitmore** [comment]
It's funny that @jonnybitcoin is voting against @cassiopaia's worker proposal.

**Comment by jonnybitcoin** [comment]
I voted against the proposal when I saw there had been no work done on either the GUI or website since we started paying him 27k a day from jan 16th. It's called be a diligent shareholder.

**Comment by c055** [comment]
funny on this nobody is mention the endless hours of voluntary contribution oer the past 3 years etc.  or during the delegate paid times .. were most of us worked for less then usual salaries .. anyway .. u are right with this ... so .. but for me the last time being able to care about my mum .. it was it worth ..

**Comment by jonnybitcoin** [comment]
Thank you for all the free work you have done. I am truly sorry for what you have been through recently. family always comes first.

**Comment by c055** [comment]
yep ...! But he .. you'Re right u are acting as for the DAC ... and u were the first who votes me in ..anyway .. i'm back at work .. not to 100% as it's not that easy .. but back .. let's get this site thing done asap over the next week ..

**Comment by jonnybitcoin** [comment]
Your recent github history shows commits to an ethereum based project. And it appears your worker proposal has been voted out presumably because of no recent updates. I assume you are losing interest in the project and I will post on the forum at the end of the week to try and find someone else willing rejuvenate the site unless I see some updates before then.

**Comment by c055** [comment]
i'm working for MAKER and NEXUS since 6 months ... pls go ahead! I'm thinking i won't be able to work in this manner ... so i will refund my unclaimend BTS ... then i have time to rethink and create a new site .. before getting paid .. but with usual hourly rates ... working in this way .. one day worker in one day worker voted out ... i don't want to work like this .. the business we are working in is stressful enough ..

**Comment by c055** [comment]
ok so i have some more ideas in mind .. 

for example ...why not using a animated text rotary on frontpage

Bitshares is …
… smart contract platform
… financial platform
... Exchange
... turing complete
... etc ..

another way i would also think could work is just using some kinda slider and target different audiences with on approach ..

**Comment by jonnybitcoin** [comment]
I'm a fan of very simple messages as people have very short attention spans. Yes bts is more than an exchange but a simple message will be understood and remembered better.
For the central text I would put something like:
- Trade on a blockchain. 
- Own shares in the worlds first fully decentralised exchange
- Exchange on a Blockchain.
- Welcome to the the decentralised exchange
- Bitshares 2.0 is an exchange on a blockchain
- decentralised dollars traded on a blockchain
- Bitshares is a fully decentralised exchange

**Comment by c055** [comment]
let me go over later this day .. not promised .. as i'm also on GUI related things today.. but will try to ..

**Comment by jonnybitcoin** [comment]
The front page of our website should just say     "Bitshares - Your share in a Decentralised Exchange"

Sub header could be animated text rotary saying:
- Fiat pegged smartcoins
- 100,000 transactions per second 
- Free transactions for BTS holders
- Anonymous transactions
- Human readable addresses
- 1.5 sec block time
- Create you own blockchain assets
- Prediction market
